In [42]:
import numpy as np

In [43]:
# ejercicio 1

In [44]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [45]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [47]:
# otra opcion

In [48]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [49]:
## otra forma

In [50]:
ndim1 = np.random.random([6])
ndim1

array([0.59224583, 0.35303144, 0.26742441, 0.640799  , 0.92441459,
       0.57602337])

In [51]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.80832596, 0.37579979],
       [0.30393124, 0.99915169],
       [0.68357843, 0.88629141]])

In [52]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.74620025, 0.90423018, 0.00422127],
        [0.78312138, 0.24862686, 0.19355228]],

       [[0.24920443, 0.56916572, 0.6522561 ],
        [0.41647524, 0.74363202, 0.91871848]],

       [[0.76686025, 0.90778985, 0.97261797],
        [0.98027098, 0.76623877, 0.94529126]],

       [[0.39687015, 0.9068999 , 0.98618472],
        [0.52021568, 0.35714956, 0.44756247]]])

In [53]:
#ejercicio 2

In [54]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [55]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [56]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'

In [57]:
## Ejercicio 3

In [58]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [59]:
arr[-1,-1,-1]

24

In [60]:
arr[0,1,:]

array([4, 5, 6])

In [61]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [62]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [63]:
arr[2,1,0]

16

In [64]:
arr[::2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [65]:
## ejercicio 4

In [66]:
adim3 =np.random.random([3,3])
adim3

array([[0.31203384, 0.18949187, 0.84857978],
       [0.72925901, 0.12207249, 0.45162653],
       [0.44968021, 0.17947221, 0.91855221]])

In [67]:
def arraydim (x):
    return np.random.random([x,x])*100


In [68]:
arraydim(2)

array([[71.36866413,  0.24034193],
       [24.16132243, 64.64234418]])

In [69]:
## Ejercicio 5

In [70]:
def matriz_bor1 (n):
    aux = np.full([n,n],1)
    aux[1:n-1,1:n-1]=0
    return aux



In [71]:
matriz_bor1(5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [72]:
## variante

In [73]:
def matriz_born (n):
    aux = np.full([n,n],n)
    aux[1:n-1,1:n-1]=0
    return aux

matriz_born(5)

array([[5, 5, 5, 5, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 5, 5, 5, 5]])

In [74]:
## Ejercicio 6

In [75]:
aux = np.ones([3,3])
aux[1,1]= np.nan
aux[2,0]= np.nan
aux

array([[ 1.,  1.,  1.],
       [ 1., nan,  1.],
       [nan,  1.,  1.]])

In [76]:
np.ndim(aux)

2

In [77]:
aux3 = aux.flatten()
aux3

array([ 1.,  1.,  1.,  1., nan,  1., nan,  1.,  1.])

In [78]:
np.isnan (aux3)

array([False, False, False, False,  True, False,  True, False, False])

In [79]:
sum(np.isnan (aux3))

2

In [80]:
def calc_dimy_nan(ar):
    print(np.ndim(ar))
    print(sum(np.isnan (ar.flatten())))


In [81]:
calc_dimy_nan(aux)

2
2


In [82]:
## EJERCICIO 7