In [1]:
import numpy as np

In [2]:
# ejercicio 1

In [ ]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [ ]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
# otra opcion

In [ ]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
## otra forma

In [9]:
ndim1 = np.random.random([6])
ndim1

array([0.35225217, 0.70610031, 0.90413959, 0.10595309, 0.93885147,
       0.68113868])

In [10]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.11876592, 0.42864253],
       [0.28206058, 0.31363049],
       [0.7679537 , 0.18511467]])

In [11]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.01717565, 0.49178451, 0.65566312],
        [0.49797901, 0.02519337, 0.8661584 ]],

       [[0.88893441, 0.52731786, 0.14855977],
        [0.96333285, 0.57902015, 0.56387365]],

       [[0.55391908, 0.91417634, 0.79529392],
        [0.84391025, 0.43440187, 0.52083338]],

       [[0.26327681, 0.87512378, 0.71666777],
        [0.40645987, 0.66718873, 0.52950221]]])

In [12]:
#ejercicio 2

In [13]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [14]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [15]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'

In [16]:
## Ejercicio 3

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [18]:
arr[-1,-1,-1]

24

In [19]:
arr[0,1,:]

array([4, 5, 6])

In [ ]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [ ]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [22]:
arr[2,1,0]

16

In [23]:
arr[::2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
## ejercicio 4

In [ ]:
adim3 =np.random.random([3,3])
adim3

array([[0.9579506 , 0.45045457, 0.61929033],
       [0.77252066, 0.57746005, 0.93686475],
       [0.35515948, 0.57378153, 0.34982692]])

In [26]:
def arraydim (x):
    return np.random.random([x,x])*100


In [ ]:
arraydim(2)

array([[ 0.57825574, 22.0675719 ],
       [92.2424268 , 44.18634981]])

In [28]:
## Ejercicio 5

In [29]:
def matriz_bor1 (n):
    aux = np.full([n,n],1)
    aux[1:n-1,1:n-1]=0
    return aux



In [ ]:
matriz_bor1(5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [31]:
## variante

In [ ]:
def matriz_born (n):
    aux = np.full([n,n],n)
    aux[1:n-1,1:n-1]=0
    return aux

matriz_born(5)

array([[5, 5, 5, 5, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 5, 5, 5, 5]])

In [33]:
## Ejercicio 6

In [34]:
aux = np.ones([3,3])
aux[1,1]= np.nan
aux[2,0]= np.nan
aux

array([[ 1.,  1.,  1.],
       [ 1., nan,  1.],
       [nan,  1.,  1.]])

In [38]:
np.ndim(aux)

2