In [1]:
import numpy as np

In [2]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
a1[a1>1]

array([2, 3])

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np. concatenate((arr1,arr2),1)
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [6]:
arr = np.array([1, 2, np.nan, 7, 4, 0])
print (arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [7]:
for pos in range(len(arr)):
    if np.isnan(arr[pos]):
        arr[pos]= 0
print(arr)

[1. 2. 0. 7. 4. 0.]


In [8]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([1., 2., 0., 7., 4., 0.])

In [9]:
arr[np.logical_not(np.isnan(arr))]

array([1., 2., 0., 7., 4., 0.])

In [10]:
arr[np.isfinite(arr)]

array([1., 2., 0., 7., 4., 0.])

In [11]:
copia = arr.copy()
vista = arr.view()

print('original:',arr)
print('copia:',copia)
print('vista:',vista)

arr[0] = 67

print('original:',arr)
print('copia:',copia)
print('vista:',vista)


original: [1. 2. 0. 7. 4. 0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [1. 2. 0. 7. 4. 0.]
original: [67.  2.  0.  7.  4.  0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [67.  2.  0.  7.  4.  0.]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr.reshape([4,3])
print(arr2)
arro = arr2.reshape(12)
arro

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
a = np.array([[1,2,3],[4,5,6,]])
b = np.array([[1,1,1],[2,2,2,]])

print(a+b)
print(a**2)

[[2 3 4]
 [6 7 8]]
[[ 1  4  9]
 [16 25 36]]


In [14]:
a = np.array([[1,2],[4,5,]])
b = np.array([[1,1],[2,2,]])

print(a@b)


[[ 5  5]
 [14 14]]


In [15]:
print(np.linalg.norm(a))

6.782329983125268


In [16]:
a.T

array([[1, 4],
       [2, 5]])

In [17]:
np.linalg.det(a)

-2.9999999999999996

In [18]:
# 1x + 2y = 1
# 3x + 5y = 2

