# Ejercicios Pandas Series

1. Escribe un programa Pandas para cambiar el tipo de datos de una columna o serie dada.

```
Serie de muestra:
    Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto
Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
tipo: float64
```

In [36]:
import pandas as pd

In [37]:
## mio

s = pd.Series([100, 200,'python',300.12,400])
st = pd.to_numeric(s,'coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [38]:
## Ricardo

s = pd.Series(['100', '200', 'python', '300.12', '400'])
st = pd.to_numeric(s, errors='coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

2. Escribe un programa Pandas para convertir series de listas en una serie.

```
Ejemplo de salida:
Serie original de listas
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: objeto
Una serie:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: objeto
```

In [39]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s


0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [40]:
t = s.apply(pd.Series)
t

0      1      2
0     Red  Green  White
1     Red  Black    NaN
2  Yellow    NaN    NaN

In [41]:
u = t.stack()
u

0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object

In [42]:
v = u.reset_index(drop=True)
v

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [43]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s

s.apply(pd.Series).stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

3. Escribe un programa Pandas para agregar algunos datos a una serie existente.

```
Ejemplo de salida:
Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: objeto
```

In [44]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s)
s2 = pd.Series(['500', 'php'])
pd.concat([s, s2])

0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

In [45]:
pd.concat([s, s2], ignore_index=True)

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

4. Escribe un programa Pandas para crear otra serie con un subconjunto de datos según un valor y una condición dada.

```
Ejemplo de salida:
Serie de datos originales:
0      0
1      1
2      2

....

9      9
10    10
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
tipo: int64
```

In [46]:


s = pd.Series(list(range(11)))
print(s)

s[s <= 5]

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

5. Escribe un programa Pandas para cambiar el orden del índice de una serie dada.

```
Ejemplo de salida:
Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
tipo: int64
```

In [47]:
# s = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
s = pd.Series(data=[1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print(s)
s.reindex(['B', 'A', 'C', 'D', 'E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64


B    2
A    1
C    3
D    4
E    5
dtype: int64

6. Escribe un programa Pandas para obtener los elementos de una serie dada que no están presentes en otra serie dada.

```
Ejemplo de salida:  
Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
tipo: int64
```

In [48]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1)
print(sr2)

mask = ~sr1.isin(sr2)
sr1[mask]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


0    1
2    3
4    5
dtype: int64

7. Escribe un programa Pandas para calcular el mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie dada.

```
Ejemplo de salida:
Serie original:
Original Series:
0      3.000938
1     11.370722
2     14.612143

....

17    14.118931
18     8.247458
19     5.526727
tipo: float64

Mínimo, percentil 25, mediana, 75 y máximo de una serie dada:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]
```

In [49]:
import numpy as np

s = (pd.Series(np.random.random(20)))*10000
print(s)
t = s.describe()
t
u = t.drop(index=['count','std','50%'])
u

0     9440.020787
1     7264.034310
2     8136.634736
3     6779.060291
4     7918.743520
5     2764.359549
6     3788.865359
7     4299.742636
8     2293.549218
9     7682.878788
10    1953.939263
11    5717.884240
12    4260.314567
13    2990.606951
14    7737.301374
15    8478.548776
16    8125.373791
17    1380.050509
18    3924.221598
19    4720.225941
dtype: float64


mean    5482.817810
min     1380.050509
25%     3589.300757
75%     7782.661910
max     9440.020787
dtype: float64

8. Escribe un programa Pandas para calcular los conteos de frecuencia de cada valor único de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     7
2     1
3     6

...


37    0
38    4
39    8
dtype: objeto
Frecuencia de cada valor único de dicha serie.
0    9
2    7
9    6
....
3    2
4    1
5    1
tipo: int64
```

In [50]:
import numpy as np

nums = np.random.randint(1, 10, [40])
print (nums)
so = pd.Series(nums)
print(so)


[5 1 6 9 9 1 3 4 1 6 4 1 3 8 2 6 2 1 4 7 8 2 4 3 2 2 3 3 9 5 5 9 4 5 9 2 1
 6 6 4]
0     5
1     1
2     6
3     9
4     9
5     1
6     3
7     4
8     1
9     6
10    4
11    1
12    3
13    8
14    2
15    6
16    2
17    1
18    4
19    7
20    8
21    2
22    4
23    3
24    2
25    2
26    3
27    3
28    9
29    5
30    5
31    9
32    4
33    5
34    9
35    2
36    1
37    6
38    6
39    4
dtype: int64


In [51]:
fso = so.value_counts()
print(fso)

1    6
4    6
2    6
6    5
9    5
3    5
5    4
8    2
7    1
dtype: int64


9. Escribe un programa Pandas para mostrar el valor más frecuente en una serie dada y reemplazar todo lo demás con el valor 'Otro'.

```
Ejemplo de salida:
Serie original:
0     3
1     1
2     1
3     3
...
12    2
13    3
14    3
dtype: int64

frecuencias principales: 
2    6
3    5
1    4
tipo: int64

0     Otro
1     Otro
2     Otro
3     Otro
...
11        2
12        2
13    Otro
14    Otro
dtype: objeto
```

**Tip**: usar isin (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html)

In [52]:
import numpy as np

In [53]:
nums = np.random.randint(1, 5, [15])
s = pd.Series(nums)
print(s)
conteo = s.value_counts()
print(conteo)
print(conteo.index)
print(conteo.index[0])
mask = ~s.isin([conteo.index[0]])
s[mask]='Otro'
s


0     2
1     2
2     2
3     3
4     3
5     1
6     3
7     2
8     1
9     1
10    2
11    4
12    2
13    4
14    1
dtype: int64
2    6
1    4
3    3
4    2
dtype: int64
Int64Index([2, 1, 3, 4], dtype='int64')
2


0        2
1        2
2        2
3     Otro
4     Otro
5     Otro
6     Otro
7        2
8     Otro
9     Otro
10       2
11    Otro
12       2
13    Otro
14    Otro
dtype: object

10. Escribe un programa Pandas para obtener las posiciones de los elementos de una serie dada en otra serie dada.

```
Ejemplo de salida:  
Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
tipo: int64
0     1
1     3
2     5
3     7
4    10
tipo: int64
Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]
```

In [54]:
import numpy as np

num1 = np.arange(1,11)
print(num1)
ser = pd.Series(num1)
print(ser)
num2 = np.arange(1,10,2)
num2[4] = 10
print(num2)
ser2 = pd.Series(num2)
print(ser2)

mask = ser.isin(ser2)
print(mask)
ser[mask]


[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
[ 1  3  5  7 10]
0     1
1     3
2     5
3     7
4    10
dtype: int64
0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8    False
9     True
dtype: bool


0     1
2     3
4     5
6     7
9    10
dtype: int64

11. Escribe un programa Pandas que convierta el primer y el último carácter de cada palabra a mayúsculas en cada palabra de una serie dada.

```
Ejemplo de salida:
Serie original:
0       php
1    python
2      java
3        c#
dtype: objeto

Primer y último carácter de cada palabra en mayúscula:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: objeto
```

In [72]:

def mayu(l):
    for x in l:
        x = 'x'.title
    print(l)
palab = pd.Series(['php','python','java','c#'])
print(palab)
k = list(palab)
print(mayu(k))


0       php
1    python
2      java
3        c#
dtype: object
['php', 'python', 'java', 'c#']
None


12. Escribe un programa Pandas para calcular la diferencia de diferencias entre números consecutivos de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
tipo: int64

Diferencia de diferencias entre números consecutivos de la serie:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
```