# Ejercicios Pandas Series

1. Escribe un programa Pandas para cambiar el tipo de datos de una columna o serie dada.

```
Serie de muestra:
    Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto
Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
tipo: float64
```

In [2]:
import pandas as pd

In [3]:
## mio

s = pd.Series([100, 200,'python',300.12,400])
st = pd.to_numeric(s,'coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [4]:
## Ricardo

s = pd.Series(['100', '200', 'python', '300.12', '400'])
st = pd.to_numeric(s, errors='coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

2. Escribe un programa Pandas para convertir series de listas en una serie.

```
Ejemplo de salida:
Serie original de listas
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: objeto
Una serie:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: objeto
```

In [5]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s


0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [6]:
t = s.apply(pd.Series)
t

0      1      2
0     Red  Green  White
1     Red  Black    NaN
2  Yellow    NaN    NaN

In [7]:
u = t.stack()
u

0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object

In [8]:
v = u.reset_index(drop=True)
v

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [9]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s

s.apply(pd.Series).stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

3. Escribe un programa Pandas para agregar algunos datos a una serie existente.

```
Ejemplo de salida:
Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: objeto
```

In [10]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s)
s2 = pd.Series(['500', 'php'])
pd.concat([s, s2])

0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

In [11]:
pd.concat([s, s2], ignore_index=True)

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

4. Escribe un programa Pandas para crear otra serie con un subconjunto de datos según un valor y una condición dada.

```
Ejemplo de salida:
Serie de datos originales:
0      0
1      1
2      2

....

9      9
10    10
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
tipo: int64
```

In [12]:


s = pd.Series(list(range(11)))
print(s)

s[s <= 5]

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

5. Escribe un programa Pandas para cambiar el orden del índice de una serie dada.

```
Ejemplo de salida:
Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
tipo: int64
```

In [13]:
# s = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
s = pd.Series(data=[1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print(s)
s.reindex(['B', 'A', 'C', 'D', 'E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64


B    2
A    1
C    3
D    4
E    5
dtype: int64

6. Escribe un programa Pandas para obtener los elementos de una serie dada que no están presentes en otra serie dada.

```
Ejemplo de salida:  
Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
tipo: int64
```

In [14]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1)
print(sr2)

mask = ~sr1.isin(sr2)
sr1[mask]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


0    1
2    3
4    5
dtype: int64

7. Escribe un programa Pandas para calcular el mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie dada.

```
Ejemplo de salida:
Serie original:
Original Series:
0      3.000938
1     11.370722
2     14.612143

....

17    14.118931
18     8.247458
19     5.526727
tipo: float64

Mínimo, percentil 25, mediana, 75 y máximo de una serie dada:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]
```

In [15]:
import numpy as np

s = (pd.Series(np.random.random(20)))*10000
print(s)
t = s.describe()
t
u = t.drop(index=['count','std','50%'])
u

0     8821.137295
1     4186.585848
2     2774.061967
3     4410.989781
4     5455.510724
5     9946.186769
6     1397.400110
7      379.825160
8     1247.856582
9     9092.163598
10    6134.377023
11    8465.950290
12    9315.263340
13    4580.402306
14    4883.433288
15     149.170494
16     164.649064
17    6948.478889
18    2543.058360
19    3088.224499
dtype: float64


mean    4699.236269
min      149.170494
25%     2256.643797
75%     7327.846739
max     9946.186769
dtype: float64

8. Escribe un programa Pandas para calcular los conteos de frecuencia de cada valor único de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     7
2     1
3     6

...


37    0
38    4
39    8
dtype: objeto
Frecuencia de cada valor único de dicha serie.
0    9
2    7
9    6
....
3    2
4    1
5    1
tipo: int64
```

In [16]:
import numpy as np

nums = np.random.randint(1, 10, [40])
print (nums)
so = pd.Series(nums)
print(so)


[4 4 9 6 8 6 5 8 2 3 4 4 4 4 5 8 3 5 2 5 9 9 1 6 3 7 3 5 2 1 6 9 6 6 1 6 4
 6 8 9]
0     4
1     4
2     9
3     6
4     8
5     6
6     5
7     8
8     2
9     3
10    4
11    4
12    4
13    4
14    5
15    8
16    3
17    5
18    2
19    5
20    9
21    9
22    1
23    6
24    3
25    7
26    3
27    5
28    2
29    1
30    6
31    9
32    6
33    6
34    1
35    6
36    4
37    6
38    8
39    9
dtype: int64


In [17]:
fso = so.value_counts()
print(fso)

6    8
4    7
9    5
5    5
8    4
3    4
2    3
1    3
7    1
dtype: int64


9. Escribe un programa Pandas para mostrar el valor más frecuente en una serie dada y reemplazar todo lo demás con el valor 'Otro'.

```
Ejemplo de salida:
Serie original:
0     3
1     1
2     1
3     3
...
12    2
13    3
14    3
dtype: int64

frecuencias principales: 
2    6
3    5
1    4
tipo: int64

0     Otro
1     Otro
2     Otro
3     Otro
...
11        2
12        2
13    Otro
14    Otro
dtype: objeto
```

**Tip**: usar isin (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html)

In [18]:
import numpy as np

In [19]:
nums = np.random.randint(1, 5, [15])
s = pd.Series(nums)
print(s)
conteo = s.value_counts()
print(conteo)
print(conteo.index)
print(conteo.index[0])
mask = ~s.isin([conteo.index[0]])
s[mask]='Otro'
s


0     3
1     2
2     4
3     1
4     1
5     1
6     3
7     3
8     4
9     1
10    2
11    3
12    1
13    4
14    3
dtype: int64
3    5
1    5
4    3
2    2
dtype: int64
Int64Index([3, 1, 4, 2], dtype='int64')
3


0        3
1     Otro
2     Otro
3     Otro
4     Otro
5     Otro
6        3
7        3
8     Otro
9     Otro
10    Otro
11       3
12    Otro
13    Otro
14       3
dtype: object

10. Escribe un programa Pandas para obtener las posiciones de los elementos de una serie dada en otra serie dada.

```
Ejemplo de salida:  
Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
tipo: int64
0     1
1     3
2     5
3     7
4    10
tipo: int64
Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]
```

In [20]:
import numpy as np

num1 = np.arange(1,11)
print(num1)
ser = pd.Series(num1)
print(ser)
num2 = np.arange(1,10,2)
num2[4] = 10
print(num2)
ser2 = pd.Series(num2)
print(ser2)

mask = ser.isin(ser2)
print(mask)
ser[mask]


[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
[ 1  3  5  7 10]
0     1
1     3
2     5
3     7
4    10
dtype: int64
0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8    False
9     True
dtype: bool


0     1
2     3
4     5
6     7
9    10
dtype: int64

## otra forma

In [21]:
series1= pd.Series([1,2,3,4,5,6,7,8,9,10])
series2= pd.Series([1,3,5,7,10])

print(series1)
print(series2)

aux = pd.Index(series1)
print(aux)
aux.get_loc(1) ## me localiza en que posición esta 1 en la lista aux
print(aux.get_loc(1)) 
aux1 = aux.get_loc(1) 
print(aux1) 
aux2 = [aux.get_loc(i) for i in series2] 
print(aux2) 

result = [pd.Index(series1).get_loc(i) for i in series2] # de una vez
print(result)





0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64
Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')
0
0
[0, 2, 4, 6, 9]
[0, 2, 4, 6, 9]


11. Escribe un programa Pandas que convierta el primer y el último carácter de cada palabra a mayúsculas en cada palabra de una serie dada.

```
Ejemplo de salida:
Serie original:
0       php
1    python
2      java
3        c#
dtype: objeto

Primer y último carácter de cada palabra en mayúscula:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: objeto
```

In [42]:
palab = pd.Series(['php','python','java','c#'])
print(palab)

result = palab.apply(lambda x: x[0].upper() + x [1:-1] +x[-1].upper())
result




0       php
1    python
2      java
3        c#
dtype: object


0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

12. Escribe un programa Pandas para calcular la diferencia de diferencias entre números consecutivos de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
tipo: int64

Diferencia de diferencias entre números consecutivos de la serie:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
```

In [47]:
serO = pd.Series([1,3,5,8,10,11,15])
print (serO)

diff1 = serO.diff().tolist()
print(diff1)

diff2 = serO.diff().diff().tolist()
print(diff2)

0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
