# Ejercicios Pandas Series

1. Escribe un programa Pandas para cambiar el tipo de datos de una columna o serie dada.

```
Serie de muestra:
    Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto
Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
tipo: float64
```

In [1]:
import pandas as pd

In [2]:
## mio

s = pd.Series([100, 200,'python',300.12,400])
st = pd.to_numeric(s,'coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [3]:
## Ricardo

s = pd.Series(['100', '200', 'python', '300.12', '400'])
st = pd.to_numeric(s, errors='coerce')
st

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

2. Escribe un programa Pandas para convertir series de listas en una serie.

```
Ejemplo de salida:
Serie original de listas
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: objeto
Una serie:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: objeto
```

In [16]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s


0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object

In [17]:
t = s.apply(pd.Series)
t

0      1      2
0     Red  Green  White
1     Red  Black    NaN
2  Yellow    NaN    NaN

In [18]:
u = t.stack()
u

0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object

In [24]:
v = u.reset_index(drop=True)
v

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [25]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])
s

s.apply(pd.Series).stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

3. Escribe un programa Pandas para agregar algunos datos a una serie existente.

```
Ejemplo de salida:
Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: objeto

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: objeto
```

In [27]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s)
s2 = pd.Series(['500', 'php'])
pd.concat([s, s2])

0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

In [28]:
pd.concat([s, s2], ignore_index=True)

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

4. Escribe un programa Pandas para crear otra serie con un subconjunto de datos según un valor y una condición dada.

```
Ejemplo de salida:
Serie de datos originales:
0      0
1      1
2      2

....

9      9
10    10
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
tipo: int64
```

In [33]:


s = pd.Series(list(range(11)))
print(s)

s[s <= 5]

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

5. Escribe un programa Pandas para cambiar el orden del índice de una serie dada.

```
Ejemplo de salida:
Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
tipo: int64
```

In [7]:
# s = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
s = pd.Series(data=[1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print(s)
s.reindex(['B', 'A', 'C', 'D', 'E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64


B    2
A    1
C    3
D    4
E    5
dtype: int64

6. Escribe un programa Pandas para obtener los elementos de una serie dada que no están presentes en otra serie dada.

```
Ejemplo de salida:  
Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
tipo: int64
```

In [8]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1)
print(sr2)

mask = ~sr1.isin(sr2)
sr1[mask]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


0    1
2    3
4    5
dtype: int64

7. Escribe un programa Pandas para calcular el mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie dada.

```
Ejemplo de salida:
Serie original:
Original Series:
0      3.000938
1     11.370722
2     14.612143

....

17    14.118931
18     8.247458
19     5.526727
tipo: float64

Mínimo, percentil 25, mediana, 75 y máximo de una serie dada:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]
```

In [79]:
import numpy as np

s = (pd.Series(np.random.random(20)))*10000
print(s)
t = s.describe()
t
u = t.drop(index=['count','std','50%'])
u

0      827.875329
1     6082.967417
2     8299.664487
3     2351.127406
4     4008.024957
5     4499.112062
6     6883.142078
7     9690.116513
8     9453.503856
9     4382.399354
10    3430.928931
11    4254.638411
12    5084.955267
13    6323.474363
14    2181.691603
15    9996.355642
16    1807.257023
17    8384.585704
18    4997.258978
19    4906.317662
dtype: float64


mean    5392.269852
min      827.875329
25%     3863.750951
75%     7237.272680
max     9996.355642
dtype: float64

8. Escribe un programa Pandas para calcular los conteos de frecuencia de cada valor único de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     7
2     1
3     6

...


37    0
38    4
39    8
dtype: objeto
Frecuencia de cada valor único de dicha serie.
0    9
2    7
9    6
....
3    2
4    1
5    1
tipo: int64
```

In [89]:
import numpy as np

nums = np.random.randint(1, 10, [40])
print (nums)
so = pd.Series(nums)
print(so)


[8 3 9 1 6 9 6 8 4 2 3 3 6 8 4 4 2 2 1 5 7 5 4 4 7 2 2 5 2 8 9 4 5 2 5 9 7
 9 5 7]
0     8
1     3
2     9
3     1
4     6
5     9
6     6
7     8
8     4
9     2
10    3
11    3
12    6
13    8
14    4
15    4
16    2
17    2
18    1
19    5
20    7
21    5
22    4
23    4
24    7
25    2
26    2
27    5
28    2
29    8
30    9
31    4
32    5
33    2
34    5
35    9
36    7
37    9
38    5
39    7
dtype: int64
<bound method IndexOpsMixin.value_counts of 0     8
1     3
2     9
3     1
4     6
5     9
6     6
7     8
8     4
9     2
10    3
11    3
12    6
13    8
14    4
15    4
16    2
17    2
18    1
19    5
20    7
21    5
22    4
23    4
24    7
25    2
26    2
27    5
28    2
29    8
30    9
31    4
32    5
33    2
34    5
35    9
36    7
37    9
38    5
39    7
dtype: int64>


In [91]:
fso = so.value_counts()
print(fso)

2    7
4    6
5    6
9    5
8    4
7    4
3    3
6    3
1    2
dtype: int64


9. Escribe un programa Pandas para mostrar el valor más frecuente en una serie dada y reemplazar todo lo demás con el valor 'Otro'.

```
Ejemplo de salida:
Serie original:
0     3
1     1
2     1
3     3
...
12    2
13    3
14    3
dtype: int64

frecuencias principales: 
2    6
3    5
1    4
tipo: int64

0     Otro
1     Otro
2     Otro
3     Otro
...
11        2
12        2
13    Otro
14    Otro
dtype: objeto
```

**Tip**: usar isin (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html)

In [9]:
import numpy as np

In [10]:
nums = np.random.randint(1, 5, [15])
s = pd.Series(nums)
print(s)
conteo = s.value_counts()
print(conteo)
print(conteo.index)
print(conteo.index[0])
mask = ~s.isin([conteo.index[0]])
s[mask]='Otro'
s


0     4
1     2
2     4
3     2
4     1
5     4
6     1
7     1
8     4
9     4
10    2
11    2
12    4
13    3
14    4
dtype: int64
4    7
2    4
1    3
3    1
dtype: int64
Int64Index([4, 2, 1, 3], dtype='int64')
4


0        4
1     Otro
2        4
3     Otro
4     Otro
5        4
6     Otro
7     Otro
8        4
9        4
10    Otro
11    Otro
12       4
13    Otro
14       4
dtype: object

10. Escribe un programa Pandas para obtener las posiciones de los elementos de una serie dada en otra serie dada.

```
Ejemplo de salida:  
Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
tipo: int64
0     1
1     3
2     5
3     7
4    10
tipo: int64
Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]
```

In [109]:
import numpy as np

num1 = np.arange(1,11)
print(num1)
ser = pd.Series(num1)
print(ser)
num2 = np.arange(1,10,2)
num2[4] = 10
print(num2)
ser2 = pd.Series(num2)
print(ser2)

s3 = pd.Series(pd.ser2pd.ser)


[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
[ 1  3  5  7 10]
0     1
1     3
2     5
3     7
4    10
dtype: int64


ValueError: Can only compare identically-labeled Series objects

11. Escribe un programa Pandas que convierta el primer y el último carácter de cada palabra a mayúsculas en cada palabra de una serie dada.

```
Ejemplo de salida:
Serie original:
0       php
1    python
2      java
3        c#
dtype: objeto

Primer y último carácter de cada palabra en mayúscula:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: objeto
```

12. Escribe un programa Pandas para calcular la diferencia de diferencias entre números consecutivos de una serie dada.

```
Ejemplo de salida:
Serie original:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
tipo: int64

Diferencia de diferencias entre números consecutivos de la serie:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
```