# Limpieza de datos

### Valores perdidos

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('./data/housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [20]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [21]:
dfdel = df.dropna()
dfdel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [22]:
## No en este caso (los datos nulos solo son  207 frente a 20433 posiciones).
# # pero en caso de un numero de datos nulos elevados suele ser conveniente sustituir los datos nulos
#  por la media o la mediana y asi alterar menos la muestra que si los eliminamos.

In [23]:
media = df['total_bedrooms'].mean()
print(media)
df['total_bedrooms'].fillna(media,inplace=True)
df.info()
df.describe()

537.8705525375618
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20640.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        419.266592   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    787.000000    280.000000       2.563400   
50%        438.000000   1166.000000    409.000000       3.534800   
75%        643.250000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [44]:
## o con la mediana

mediana = df['total_bedrooms'].median()
print(mediana)
df['total_bedrooms'].fillna(mediana,inplace=True)
df.info()
df.describe()

438.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20640.000000  20640.000000  20640.000000   20640.000000   
mean       536.868944   1425.476744    499.539680       3.870671   
std        419.384678   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    787.000000    280.000000       2.563400   
50%        438.000000   1166.000000    409.000000       3.534800   
75%        643.250000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

 ### Valores atípicos

In [25]:
import numpy as np

np.random.seed(0)
data = np.random.randint(low=0, high=11, size=1000)
data[0] = 100
data[1] = -100

data



array([ 100, -100,    3,    3,    7,    9,    3,    5,    2,    4,    7,
          6,    8,    8,   10,    1,    6,    7,    7,    8,    1,    5,
          9,    8,    9,    4,    3,    0,    3,    5,    0,    2,    3,
          8,    1,    3,    3,    3,    7,    0,    1,    9,    9,    0,
         10,    4,    7,    3,    2,    7,    2,    0,    0,    4,    5,
          5,    6,    8,    4,    1,    4,    9,   10,   10,    8,    1,
          1,    7,    9,    9,    3,    6,    7,    2,    0,    3,    5,
          9,   10,    4,    4,    6,    4,    4,    3,    4,    4,    8,
          4,    3,   10,    7,    5,    5,    0,    1,    5,    9,    3,
          0,    5,    0,    1,    2,    4,    2,    0,    3,    2,   10,
          0,    7,    5,    9,    0,   10,    2,   10,    7,    2,    9,
          2,    3,    3,    2,    3,    4,    1,    2,    9,   10,    1,
          4,   10,    6,    8,    2,    3,    0,    0,    6,    0,    6,
          3,   10,    3,    8,    8,    8,    2,   

In [26]:
z_scores=(data-np.mean(data))/np.std(data)
z_scores

array([ 1.74668874e+01, -1.92718622e+01, -3.51406141e-01, -3.51406141e-01,
        3.83368853e-01,  7.50756349e-01, -3.51406141e-01,  1.59813561e-02,
       -5.35099889e-01, -1.67712392e-01,  3.83368853e-01,  1.99675104e-01,
        5.67062601e-01,  5.67062601e-01,  9.34450098e-01, -7.18793637e-01,
        1.99675104e-01,  3.83368853e-01,  3.83368853e-01,  5.67062601e-01,
       -7.18793637e-01,  1.59813561e-02,  7.50756349e-01,  5.67062601e-01,
        7.50756349e-01, -1.67712392e-01, -3.51406141e-01, -9.02487385e-01,
       -3.51406141e-01,  1.59813561e-02, -9.02487385e-01, -5.35099889e-01,
       -3.51406141e-01,  5.67062601e-01, -7.18793637e-01, -3.51406141e-01,
       -3.51406141e-01, -3.51406141e-01,  3.83368853e-01, -9.02487385e-01,
       -7.18793637e-01,  7.50756349e-01,  7.50756349e-01, -9.02487385e-01,
        9.34450098e-01, -1.67712392e-01,  3.83368853e-01, -3.51406141e-01,
       -5.35099889e-01,  3.83368853e-01, -5.35099889e-01, -9.02487385e-01,
       -9.02487385e-01, -

In [27]:
umbral = 3
outliers = np.where(np.abs(z_scores) > umbral)
outliers

(array([0, 1]),)

In [28]:
data[outliers]

array([ 100, -100])

In [47]:
# lo mismo para el df de las casas

z_scores=(df-np.mean(df))/np.std(df)
#print(z_scores)
umbral = 3
outliers = np.where(np.abs(z_scores) > umbral)
#print(outliers)

dfout_mask=~df.where(np.abs(z_scores) > umbral).isna()
dfout_mask

/anaconda/envs/azureml_py38/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/anaconda/envs/azureml_py38/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3571: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  median_house_value  \
0           False       False          False               False   
1           False       False          False               False   
2           False       False          False               False   
3           False       False          False               False   
4           False       False          False               False   
...           ...         ...            ...                 ...   
20635       False       False          False               False   
20636       False       False          False               False   
20637       False       False          False               False   
20638       False       False          False               False   
20639       False       False          False               False   

       ocean_proximity  
0                False  
1                False  
2                False  
3                False  
4                False  
...                ...  
20635            False  
20636            False  
20637            False  
20638            False  
20639            False  

[20640 rows x 10 columns]

In [55]:
q1 = np.percentile(data,25)
q3 = np.percentile(data,75)
iqr = q3 - q1
print(iqr)
print(np.mean(data))

umbra_sup = q3 + (1.5*iqr)
umbra_inf = q1 - (1.5*iqr)
print('umbrales:', umbra_inf, umbra_sup)

outliers = np.where((data < umbra_inf) | (data > umbra_sup))
outliers
data[outliers]


6.0
4.913
umbrales: -7.0 17.0


array([ 100, -100])

In [58]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [75]:
c_numericas =['housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']
df_num= df[c_numericas]

q1 = df_num.apply(lambda x: np.percentile(x,25))
q3 = df_num.apply(lambda x: np.percentile(x,75))

iqr = q3 - q1
print('iqr:',iqr,'\n')
#print(q1,q3)

umbra_sup = q3 + (1.5*iqr)
umbra_inf = q1 - (1.5*iqr)
print('umbrales inf: \n:', umbra_inf)
print('umbrales sup: \n:', umbra_sup)

outliers = np.where((df_num< umbra_inf) | (df_num> umbra_sup))

mask = df_num.isin((df_num< umbra_inf) | (df_num> umbra_sup))
print(df_num[mask].count())

df_num.clip(lower=umbra_inf,upper=umbra_sup,axis=1)



iqr: housing_median_age        19.00000
total_rooms             1700.25000
total_bedrooms           346.25000
population               938.00000
households               325.00000
median_income              2.17985
median_house_value    145125.00000
dtype: float64 

umbrales inf: 
: housing_median_age      -10.500000
total_rooms           -1102.625000
total_bedrooms         -222.375000
population             -620.000000
households             -207.500000
median_income            -0.706375
median_house_value   -98087.500000
dtype: float64
umbrales sup: 
: housing_median_age        65.500000
total_rooms             5698.375000
total_bedrooms          1162.625000
population              3132.000000
households              1092.500000
median_income              8.013025
median_house_value    482412.500000
dtype: float64
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtyp

housing_median_age  total_rooms  total_bedrooms  population  \
0                    41.0      880.000           129.0       322.0   
1                    21.0     5698.375          1106.0      2401.0   
2                    52.0     1467.000           190.0       496.0   
3                    52.0     1274.000           235.0       558.0   
4                    52.0     1627.000           280.0       565.0   
...                   ...          ...             ...         ...   
20635                25.0     1665.000           374.0       845.0   
20636                18.0      697.000           150.0       356.0   
20637                17.0     2254.000           485.0      1007.0   
20638                18.0     1860.000           409.0       741.0   
20639                16.0     2785.000           616.0      1387.0   

       households  median_income  median_house_value  
0           126.0       8.013025            452600.0  
1          1092.5       8.013025            358500.0  
2           177.0       7.257400            352100.0  
3           219.0       5.643100            341300.0  
4           259.0       3.846200            342200.0  
...           ...            ...                 ...  
20635       330.0       1.560300             78100.0  
20636       114.0       2.556800             77100.0  
20637       433.0       1.700000             92300.0  
20638       349.0       1.867200             84700.0  
20639       530.0       2.388600             89400.0  

[20640 rows x 7 columns]

In [10]:
import numpy as np

np.random.seed(0)
data = np.random.randint(low=0, high=11, size=1000)
data[0] = 100
data[1] = -100


data = {'customer_id': [102, 102, 101, 103, 102], 'product_id': [
    'A', 'B', 'A', 'C', 'B'], 'quantity_sold': [5, 3, 2, 1, 4]}
df = pd.DataFrame(data)