In [1]:
import numpy as np

In [2]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
a1[a1>1]

array([2, 3])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np. concatenate((arr1,arr2),1)
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
arr = np.array([1, 2, np.nan, 7, 4, 0])
print (arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [21]:
for pos in range(len(arr)):
    if np.isnan(arr[pos]):
        arr[pos]= 0
print(arr)

[1. 2. 0. 7. 4. 0.]


In [28]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([1., 2., 7., 4., 0.])

In [29]:
arr[np.logical_not(np.isnan(arr))]

array([1., 2., 7., 4., 0.])

In [34]:
arr[np.isfinite(arr)]

array([1., 2., 7., 4., 0.])

In [39]:
copia = arr.copy()
vista = arr.view()

print('original:',arr)
print('copia:',copia)
print('vista:',vista)

arr[0] = 67

print('original:',arr)
print('copia:',copia)
print('vista:',vista)


original: [67.  2. nan  7.  4.  0.]
copia: [67.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]
original: [67.  2. nan  7.  4.  0.]
copia: [67.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]
