In [50]:
import numpy as np

In [51]:
# ejercicio 1

In [52]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [53]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [55]:
# otra opcion

In [56]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [57]:
## otra forma

In [58]:
ndim1 = np.random.random([6])
ndim1

array([0.49410985, 0.7637442 , 0.09004073, 0.4409383 , 0.79419737,
       0.56208448])

In [59]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.68542711, 0.51661784],
       [0.45970958, 0.649712  ],
       [0.33087841, 0.85656371]])

In [60]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.55274456, 0.3837013 , 0.06790173],
        [0.54350483, 0.34652492, 0.06064977]],

       [[0.56102094, 0.0534179 , 0.79200147],
        [0.6868586 , 0.34778134, 0.07238024]],

       [[0.64570648, 0.60529241, 0.22844859],
        [0.20400143, 0.8941002 , 0.29027252]],

       [[0.56257894, 0.37521275, 0.74151206],
        [0.76775452, 0.73991696, 0.10261034]]])

In [61]:
#ejercicio 2

In [62]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [63]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [64]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'

In [65]:
## Ejercicio 3

In [66]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [67]:
arr[-1,-1,-1]

24

In [68]:
arr[0,1,:]

array([4, 5, 6])

In [69]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [70]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [76]:
arr[2,1,0]

16

In [79]:
arr[::2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [80]:
## ejercicio 4

In [82]:
adim3 =np.random.random([3,3])
adim3

array([[0.03360331, 0.81511634, 0.78781877],
       [0.36718789, 0.0823928 , 0.94791273],
       [0.47883171, 0.40191437, 0.28251894]])

In [84]:
def arraydim (x):
    return np.random.random([x,x])*100


In [89]:
arraydim(2)

array([[76.16194482, 34.22008213],
       [84.29775637, 57.61965459]])

In [90]:
## Ejercicio 5

In [96]:
aux = np.full([5,5],5)
aux

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
stack