In [1]:
import numpy as np

In [2]:
# ejercicio 1

In [ ]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [4]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
# otra opcion

In [7]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
## otra forma

In [9]:
ndim1 = np.random.random([6])
ndim1

array([0.77227721, 0.69680841, 0.27527455, 0.04082806, 0.63753064,
       0.96012814])

In [10]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.37603423, 0.47385611],
       [0.2687413 , 0.93318788],
       [0.47237905, 0.2877441 ]])

In [11]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.70950597, 0.47636833, 0.89530239],
        [0.39493897, 0.53128937, 0.10990459]],

       [[0.0676349 , 0.31210358, 0.70761702],
        [0.5166659 , 0.08103655, 0.63673396]],

       [[0.19783922, 0.82205205, 0.64130999],
        [0.68360576, 0.41336453, 0.2840136 ]],

       [[0.62404844, 0.4035078 , 0.64242906],
        [0.20900946, 0.21399088, 0.7767051 ]]])

In [12]:
#ejercicio 2

In [13]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [14]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [15]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'

In [16]:
## Ejercicio 3

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [18]:
arr[-1,-1,-1]

24

In [19]:
arr[0,1,:]

array([4, 5, 6])

In [20]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [21]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [22]:
arr[2,1,0]

16

In [23]:
arr[::2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
## ejercicio 4

In [25]:
adim3 =np.random.random([3,3])
adim3

array([[0.88028701, 0.3244379 , 0.35164767],
       [0.98694447, 0.55974647, 0.18614818],
       [0.63687421, 0.35163855, 0.79994178]])

In [26]:
def arraydim (x):
    return np.random.random([x,x])*100


In [27]:
arraydim(2)

array([[47.26063505, 52.50573181],
       [37.3330301 , 42.54743501]])

In [28]:
## Ejercicio 5

In [53]:
def matriz_bor1 (n):
    aux = np.full([n,n],1)
    aux[1:n-1,1:n-1]=0
    return aux



In [54]:
matriz_bor1(5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [55]:
## variante

In [56]:
def matriz_born (n):
    aux = np.full([n,n],n)
    aux[1:n-1,1:n-1]=0
    return aux

matriz_born(5)

array([[5, 5, 5, 5, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 5, 5, 5, 5]])