In [1]:
import numpy as np

In [2]:
# ejercicio 1

In [ ]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [4]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
# otra opcion

In [7]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
## otra forma

In [9]:
ndim1 = np.random.random([6])
ndim1

array([0.01693584, 0.55122663, 0.18703067, 0.35019907, 0.07766679,
       0.55038527])

In [10]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.52142489, 0.98138156],
       [0.54067058, 0.28674344],
       [0.64874764, 0.61020676]])

In [11]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.90432055, 0.10037739, 0.10461488],
        [0.85364844, 0.68265561, 0.14014557]],

       [[0.1517938 , 0.92235452, 0.20221383],
        [0.95932306, 0.92651639, 0.59768655]],

       [[0.87254119, 0.41109505, 0.6607105 ],
        [0.00319203, 0.26337878, 0.0316753 ]],

       [[0.22462516, 0.65066246, 0.69942823],
        [0.55435736, 0.76529081, 0.2941841 ]]])

In [12]:
#ejercicio 2

In [39]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [40]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [34]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'