In [1]:
import numpy as np

In [2]:
# ejercicio 1

In [ ]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [4]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
# otra opcion

In [7]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
## otra forma

In [9]:
ndim1 = np.random.random([6])
ndim1

array([0.27311797, 0.74987038, 0.13323218, 0.37164297, 0.01705726,
       0.95898377])

In [10]:
ndim2 = np.random.random([3,2])
ndim2

array([[0.98250459, 0.28680391],
       [0.57765368, 0.9135808 ],
       [0.73491934, 0.84449317]])

In [11]:
ndim3 = np.random.random([4,2,3])
ndim3

array([[[0.14841469, 0.25412507, 0.21221507],
        [0.27278787, 0.55353099, 0.93902531]],

       [[0.81834483, 0.32931886, 0.77387445],
        [0.09623353, 0.73600274, 0.44027383]],

       [[0.11969539, 0.49633626, 0.52069415],
        [0.29630173, 0.73004326, 0.45461394]],

       [[0.13941361, 0.90456727, 0.15554855],
        [0.00252485, 0.6554274 , 0.9171737 ]]])

In [12]:
#ejercicio 2

In [13]:
def resumen_estad(arr):
    if arr.ndim != 1:
        return 'el array debe ser de 1 dimension'
    
    print('Minimo:', np.min(arr))
    print('Maximo:', np.max(arr))
    print('Media:', np.mean(arr))
    print('Mediana:',np.median(arr))
    print('Varianza:',np.var(arr))
    print('Desv std:',np.std(arr))
    print('Q1:',np.percentile(arr,25))
    print('Q2:',np.percentile(arr,50))
    print('Q3:',np.percentile(arr,75))





In [14]:
prueba = np.array([1,2,3,4,5,-5,9,123])
resumen_estad(prueba)



Minimo: -5
Maximo: 123
Media: 17.75
Mediana: 3.5
Varianza: 1596.1875
Desv std: 39.95231532714969
Q1: 1.75
Q2: 3.5
Q3: 6.0


In [15]:
prueba1= np.full([2,3],5)
print(prueba1)
resumen_estad(prueba1)

[[5 5 5]
 [5 5 5]]


'el array debe ser de 1 dimension'

In [16]:
## Ejercicio 3

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [18]:
arr[-1,-1,-1]

24

In [19]:
arr[0,1,:]

array([4, 5, 6])

In [20]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [21]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [22]:
arr[2,1,0]

16

In [23]:
arr[::2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
## ejercicio 4

In [25]:
adim3 =np.random.random([3,3])
adim3

array([[0.92509732, 0.22553777, 0.39884883],
       [0.29829779, 0.97868774, 0.95124079],
       [0.03189511, 0.58899654, 0.86093964]])

In [26]:
def arraydim (x):
    return np.random.random([x,x])*100


In [27]:
arraydim(2)

array([[7.88869386e+01, 1.79227593e-02],
       [1.92322189e+01, 4.47339892e+01]])

In [28]:
## Ejercicio 5

In [29]:
def matriz_bor1 (n):
    aux = np.full([n,n],1)
    aux[1:n-1,1:n-1]=0
    return aux



In [30]:
matriz_bor1(5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [31]:
## variante

In [32]:
def matriz_born (n):
    aux = np.full([n,n],n)
    aux[1:n-1,1:n-1]=0
    return aux

matriz_born(5)

array([[5, 5, 5, 5, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 5, 5, 5, 5]])

In [33]:
## Ejercicio 6

In [34]:
aux = np.ones([3,3])
aux[1,1]= np.nan
aux[2,0]= np.nan
aux

array([[ 1.,  1.,  1.],
       [ 1., nan,  1.],
       [nan,  1.,  1.]])

In [35]:
np.ndim(aux)

2

In [36]:
aux3 = aux.flatten()
aux3

array([ 1.,  1.,  1.,  1., nan,  1., nan,  1.,  1.])

In [37]:
np.isnan (aux3)

array([False, False, False, False,  True, False,  True, False, False])

In [38]:
sum(np.isnan (aux3))

2

In [41]:
def calc_dimy_nan(ar):
    print(np.ndim(ar))
    print(sum(np.isnan (ar.flatten())))


In [42]:
calc_dimy_nan(aux)

2
2


In [43]:
## EJERCICIO 7