In [1]:
import numpy as np

In [ ]:
# ejercicio 1

In [2]:
dim1 = np.array([1,2,3,4,5,6])
dim1

array([1, 2, 3, 4, 5, 6])

In [3]:
dim2 = np.array([[1,2],[3,4],[5,6]])
dim2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# otra opcion

In [5]:
print (np.zeros(6))
print (np.zeros([3,2]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#ejercicio 2

In [ ]:
def