In [6]:
import numpy as np


<module 'numpy' from '/anaconda/envs/azureml_py38/lib/python3.10/site-packages/numpy/__init__.py'>

In [8]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [9]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3 = np.array([[[1,2,3],[3,4,5]],[[9,10,11],[12,13,14]],[[15,16,17],[18,19,20]]])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [14]:
a1[1]


2

In [15]:
a2[1, 2]

6

In [23]:
a3[1, 0, 1]

10

In [27]:
av = np.empty([4,3])
av

array([[4.64220544e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.12465777e-312, 6.87527785e-038],
       [2.93003191e-057, 3.89051422e-033, 4.08342094e+179],
       [6.95355619e-042, 6.03369119e+174, 1.58906535e-047]])

In [28]:
az = np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
ao = np.ones([3,5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
af = np.full([3,5],9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [36]:
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [40]:
ar = np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [41]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

In [47]:
al = np.linspace(1,100,20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [67]:
aran = np.random.random([2, 3])
aran

array([[0.22512813, 0.47442801, 0.38031336],
       [0.00297202, 0.58192889, 0.66916528]])

In [51]:
aran.ndim

2

In [52]:
aran.shape

(2, 3)

In [53]:
aran.size

6

In [54]:
aran.dtype

dtype('float64')

In [58]:
at = np.array(['hola','mundo'])
at

array(['hola', 'mundo'], dtype='<U5')

In [59]:
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [60]:
np.info(al.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [68]:
al.astype('i')

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [69]:
aran

array([[0.22512813, 0.47442801, 0.38031336],
       [0.00297202, 0.58192889, 0.66916528]])

In [70]:
np.sort(aran)

array([[0.22512813, 0.38031336, 0.47442801],
       [0.00297202, 0.58192889, 0.66916528]])

In [71]:
np.sort(aran,0)

array([[0.00297202, 0.47442801, 0.38031336],
       [0.22512813, 0.58192889, 0.66916528]])

In [76]:
arr = np.array([2, 4, 5, 0, 6, 1, 5, 4, 1, -3])

In [77]:
np.min(arr)

-3

In [78]:
np.max(arr)

6

In [79]:
np.mean(arr)

2.5

In [80]:
np.median(arr)

3.0

In [81]:
np.std(arr)

2.6551836094703507

In [82]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [83]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [84]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [85]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [86]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [87]:
np.prod(arr)

0

In [92]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [94]:
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 4
2 5
3 0
4 6
5 1
6 5
7 4
8 1
9 -3


In [99]:
aran

array([[0.22512813, 0.47442801, 0.38031336],
       [0.00297202, 0.58192889, 0.66916528]])

In [101]:
for x in aran:
    for y in x:
        print(y)

0.22512813150915834
0.47442801124067524
0.38031335984143333
0.0029720240788529972
0.5819288904428035
0.6691652811259596


In [107]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [104]:
for x in a3:
    for y in x:
        for z in y:
         print(z)

1
2
3
3
4
5
9
10
11
12
13
14
15
16
17
18
19
20


In [105]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [108]:
for x in np.nditer(a3):
    print(x)

1
2
3
3
4
5
9
10
11
12
13
14
15
16
17
18
19
20


In [109]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [113]:
for pos, x in np.ndenumerate(a3):
    print(pos, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 1, 0) 12
(1, 1, 1) 13
(1, 1, 2) 14
(2, 0, 0) 15
(2, 0, 1) 16
(2, 0, 2) 17
(2, 1, 0) 18
(2, 1, 1) 19
(2, 1, 2) 20
